---
title: "Create_maps"
author: "Soria Delva"
date: "2024-10-10"
output: html_document
---

This script is written to create the PDF pages with occupancy and climate matching maps used in the final report.

# Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load libraries.

```{r Load libraries}
library(googlesheets4)
library(googledrive)
library(dplyr)
library(progress)
library(sf)
library(rnaturalearth)
library(terra)
library(mapview)
library(ggplot2)
library(ggtext)
library(here)
library(RColorBrewer)
library(patchwork)
library(stringr)
library(progress)
library(pdftools)
library(qpdf)
library(magick)
library(future)
library(future.apply)
library(parallel)
```

# Load datafiles

```{r Load datafiles}
#Data for plotting grid cells (0-5 grid cells)
maps_data<-read_sheet("1fJVAmqPBfOPV4X6D4Ci5ErJrlfERJBYgGqQ-lCJQgH4", sheet="Data",  col_types = "ncnccccccccccncnn")

#climate_matching 0-2 grid cells 5 (n = 3604 IDs)
climate_matching_0_2<-read_sheet("1Gf5-sOxQTznOUAutQFNXCaqyxZnY7PXr56v6mdXpzwE",sheet="Data")

#climate matching 3-5 grid cells (n = 254 IDs)
climate_matching_3_5<-read_sheet("1gM6j7XS4KEQY8hZPQOJXDiysp3B3IYV3FHzYCcTbJMw",sheet="Data")

##---Load datasets needed to append information---
#List with corrected thematic groups
thematic_groups<-read_sheet("1k6pSd9quV7moZ7K9sLjghbQJRihZxPP48_5obcRYS4A", sheet="Data all")%>%
  select(ID,Thematic_group)%>%
  mutate(Thematic_group=case_when(Thematic_group=="Fw Inverts"~"FW Inverts",
                                   .default=Thematic_group))


#Initial list used to extract taxonkeys for climate matching 0-2 grid cells (n=4572)
initial_CM_list_0_2<-read_sheet("1TevRYtBiBUhiPI-lRbJPuhkNAAqBhz3g3kEyKZY42YU", sheet="Data")

#Initial list used to extract taxonkeys for climate matching of species occupying 3-5 grid cells (n = 286)
initial_CM_list_3_5<-read_sheet("1XfE2LmyOOrgl-cxk0EmzWIG_9DHNtFK1r9PNXuPbKJU", sheet="Data")%>%
  filter(total_grid_cells>2 & total_grid_cells<6)

#List Irena to exclude plants that may have slipped in via correction sheet
Irena_plants_exclude<-read_sheet("1xnQW5rk50Unt9e2P6I3ULrEdxApZ1yj_nnzbSjgzlE0", sheet = "Data")%>%
  filter(DECISION%in% c("arch","native","excludeHigherTaxa"))%>%
  pull(ID)

#Sheet with gridcell data outside EU but in Europe
maps_data_outside_EU<-read_sheet("1_qs8noQW8NQl9pH_LOJ0grcPWOaw6bjWpg4C9mJCfiA", sheet = "Data", col_types = "ncnncnn")
```

# Process and prepare datasets

```{r Add right thematic groups to maps_data}
maps_data<-maps_data%>%
  left_join(thematic_groups, by = "ID", suffix = c("_old", "_new")) %>%
  mutate(Thematic_group = ifelse(is.na(Thematic_group_new), Thematic_group_old, Thematic_group_new)) %>%
  select(-Thematic_group_old, -Thematic_group_new)
```

```{r Process sheet with grid cell data outside EU but inside Europe}
#Prepare maps_data for left join, adding taxonomic info and ID (n=5362 unique species)
distinct_maps_data <- maps_data %>%
  select(c(1, 4:12))%>%
  distinct(speciesKey, .keep_all = TRUE)
  
#378 species occupy grid cells in Europe but outside EU out of 5362 species 
maps_data_outside_EU<-maps_data_outside_EU%>%
  filter(speciesKey %in% maps_data$speciesKey)%>% # 7461 rows
  left_join(distinct_maps_data, by="speciesKey") #add taxonomic info
```

```{r Process climate matching sheets 0-2 grid cells}
#--------- 0-2 grid cells------------
#Add right thematic groups to initial cm list
initial_CM_list_0_2<-initial_CM_list_0_2%>%
  left_join(thematic_groups, by = "ID", suffix = c("_old", "_new")) %>%
  mutate(Thematic_group = ifelse(is.na(Thematic_group_new), Thematic_group_old, Thematic_group_new)) %>%
  select(-Thematic_group_old, -Thematic_group_new)

#Create dataset with standardised occupation potential column
stand_occ_potential02<-climate_matching_0_2%>%
    mutate(weighted_surface=perc_climate*surface_area_climatezone/100)%>%
  group_by(scenario, speciesKey,n_totaal)%>%
  summarize(sum_weighted_surface=sum(weighted_surface),
            percentage_climatematch_EU = sum(perc_climate, na.rm = TRUE))%>%
  ungroup()%>%
  mutate(max_sum_weighted_surface= case_when(scenario=="2001-2025-A1FI"~1951756,
                                             scenario=="2026-2050-A1FI"~1843108))%>% # maximum possible value, equal to 100% in Cfb in each scenario
  mutate(ranked_weighted_surface=sum_weighted_surface/max_sum_weighted_surface*100)%>%
  select(c(speciesKey, scenario, ranked_weighted_surface))

#n =3603 IDs, add taxonomic data and standardised occupation potential to climate matching dataset
climate_matching_0_2<-climate_matching_0_2%>%
  left_join(.,initial_CM_list_0_2, by="speciesKey")%>%
  filter(!ID %in% Irena_plants_exclude)%>%
  left_join(., stand_occ_potential02, by=c("speciesKey", "scenario"))


#-----------------Add marine species--------------------
#species with thematic group marine excluded from climate matching for grid cells 0-2
marine_0_2<-read_sheet("1limsIJcHBtrJdKMMKwcK8_usdCOs0_v8u71MW1bC5w4",sheet="Data")

#species that were excluded during climate matching grid cells 0-2
marine_16<-read_sheet("14DoltaPfvDA_ZMf_x7uDRLZhMLYFG8J-KtfGEdwBi4c", sheet="Data")
marine_7<-read_sheet("1Mkyt4mzp1lr-AEG8A86ERck_pXZihqHeO0tbtiPSyx0", sheet="Data")
marine_cm<-rbind(marine_16, marine_7)

#add taxonomic info
 marine_cm<-marine_cm%>%
   left_join(.,initial_CM_list_0_2, by="speciesKey")

 #combine into one dataframe
marine_0_2<-rbind(marine_0_2, marine_cm)

#Remove marine species that are on list Irena (none)
marine_0_2<-marine_0_2%>%
  filter(!ID %in% Irena_plants_exclude)

#Remove unicellular algae (n = 6)
toremove<-marine_0_2%>%
  filter(kingdom!="Animalia")%>%
  filter(scientificName %in%c("Alexandrium monilatum (J.F.Howell) Balech, 1995",
                              "Marteilia refringens Grizel, Comps, Bonami, Cousserans, Duthoit & Le Pennec, 1974",
                              "Asteromphalus sarcophagus Wallich, 1860",
                              "Olisthodiscus luteus N.Carter, 1937",
                              "Isochrysis galbana Parke",
                              "Alexandrium leei Balech"))%>%
           pull(ID)

#This yields 875 marine species
marine_0_2<-marine_0_2%>%
  filter(!ID%in% toremove)%>%
  select(c(ID,scientificName, speciesKey,kingdom,phylum,class,order,family,genus,Source,Thematic_group,total_grid_cells))

#Create final climate matching dataset for 0-2 grid cells (n = 4478)
climate_matching_0_2<-bind_rows(climate_matching_0_2, marine_0_2)

```

```{r Process climat matching sheets 3-5 grid cells}
#Add right thematic groups to initial cm list
initial_CM_list_3_5<-initial_CM_list_3_5%>%
  left_join(thematic_groups, by = "ID", suffix = c("_old", "_new")) %>%
 mutate(Thematic_group = ifelse(is.na(Thematic_group_new), Thematic_group_old, Thematic_group_new)) %>%
  select(-Thematic_group_old, -Thematic_group_new)

#Create dataset with standardised occupation potential column
stand_occ_potential35<-climate_matching_3_5%>%
    mutate(weighted_surface=perc_climate*surface_area_climatezone/100)%>%
  group_by(scenario, speciesKey,n_totaal)%>%
  summarize(sum_weighted_surface=sum(weighted_surface),
            percentage_climatematch_EU = sum(perc_climate, na.rm = TRUE))%>%
  ungroup()%>%
  mutate(max_sum_weighted_surface= case_when(scenario=="2001-2025-A1FI"~1951756,
                                             scenario=="2026-2050-A1FI"~1843108))%>% # maximum possible value, equal to 100% in Cfb in each scenario
  mutate(ranked_weighted_surface=sum_weighted_surface/max_sum_weighted_surface*100)%>%
  select(c(speciesKey, scenario, ranked_weighted_surface))

#Add taxonomic data and standardised occupation potential to climate matching data
climate_matching_3_5<-climate_matching_3_5%>%
  left_join(.,initial_CM_list_3_5, by="speciesKey")%>%
  filter(!ID %in% Irena_plants_exclude)%>%
  select(-n_gridcells_country)%>%
  left_join(., stand_occ_potential35, by=c("speciesKey", "scenario"))

#---------Remove thematic group = Marine from list as I forgot to do that beforehand (n = 5)
marine3_5<-climate_matching_3_5%>%
  filter(Thematic_group=="Marine")%>%
  select(c(1,10:20))
climate_matching_3_5<-climate_matching_3_5%>% #249 species that were climate matched
  filter(Thematic_group!="Marine")

#-------add marine species--------------

#Read in species that were excluded during climate matching (n = 32)
marine_cm<-read_sheet("1moGtxLqtoSGhKpWcVs_L96FHudRGWMNIlKsfp3cxpy8", sheet="Data")

#Do a left join to add taxonomic information
marine_cm<-marine_cm%>%
  left_join(.,initial_CM_list_3_5, by="speciesKey")%>%
  select(-n_gridcells_country)

##Bind them together with species that were excluded because they had thematic_group "Marine"
marine3_5<-rbind(marine3_5, marine_cm)

#Remove unicellular algae (n = 3)
toremove<-marine3_5%>%
  filter(kingdom!="Animalia")%>%
  filter(scientificName %in%c("Alexandrium catenella (Whedon & Kofoid) Balech",
                              "Dicroerisma psilonereiella F.J.R.Taylor & Cattell",
                              "Pseudochattonella verruculosa (Y.Hara & Chihara) Hosoi-Tanabe, D.Honda, S.Fukaya, Y.Inagaki & Y.Sako"
                              ))%>%
  pull(ID)

#This yields 34 marine species (32 removed because of 50% occurrences, 5 included but had thematic group marine, 3 removed because unicellular algae)
marine3_5<-marine3_5%>%
  filter(!ID%in% toremove)%>%
  distinct(speciesKey, .keep_all=TRUE)%>%
  select(c(ID,scientificName, speciesKey,kingdom,phylum,class,order,family,genus,Source,Thematic_group,total_grid_cells))

#Create final climate matching dataset for 0-2 grid cells (n = 283 IDs)
climate_matching_3_5<-bind_rows(climate_matching_3_5, marine3_5)

```

```{r Load and prepare spatial data}
memberstates<-read.csv2(here("./data/input/GRIIS_checklists.csv"))%>%
  pull(EU_state)

#----------------Load shapefiles and rasters------------
eu_50raster<-rast("./data/input/eu_50raster.tif")

region_shape<-st_read("./data/spatial/ne_10m_admin_0_countries/ne_10m_admin_0_countries.shp")%>%
  filter(ADMIN%in%c(memberstates,"Czech Republic"))%>%
  st_crop(xmin=-13, ymin=20, xmax=41, ymax= 81)%>%
  select(c(ADMIN, geometry))%>%
  st_transform(crs=st_crs(eu_50raster))

#Get shapefile of EEZ of EU member states
EEZ<-st_read("./data/spatial/EEZ/EEZ_land_v2_201410.shp")%>%
  filter(Country%in% c(memberstates, "Czech Republic"))

#Erase canary islands and Azores using a custom shape file
mask_islands<-st_read("./data/spatial/EU_mask.shp") 
EEZ<-EEZ%>%
  st_difference(mask_islands)%>%
  st_transform( st_crs(eu_50raster))

#Europe
europe<-st_read("./data/spatial/ne_10m_admin_0_countries/ne_10m_admin_0_countries.shp") %>%
  filter(SOVEREIGNT%in%c(memberstates, "Czech Republic", "Norway","United Kingdom", "Switzerland","Iceland","Bosnia and Herzegovina","Albania","Andorra","Vatican","Montenegro","Netherlands","Republic of Serbia","Kosovo","Montenegro","Macedonia","Belarus","Ukraine","Moldova","Monaco","Northern Cyprus"),
         ADMIN!="Greenland")%>%
  st_crop(xmin=-25, ymin=20, xmax=41, ymax= 70)%>%
  st_transform( st_crs(eu_50raster))

mapview(europe)

```

```{r Combine them into one main file and add spatial data}
#n = 34402
climate_matching<-rbind(climate_matching_0_2, climate_matching_3_5)

# Load climate layers
load("./data/input/climate_matching/future.rda")
load("./data/input/climate_matching/legends.rda")
load("./data/input/climate_matching/observed.rda")

# Import legends
KG_Rubel_Kotteks_Legend <- legends$KG_A1FI

#Prepare dataframes
climate_matching_all<-climate_matching%>%
  filter(is.na(Classification))
climate_matching<-climate_matching%>%
  filter(!is.na(Classification))

for (t in unique(climate_matching$scenario)){
  obs_shape <- future[[t]]%>%
    mutate(GRIDCODE= as.double(GRIDCODE))%>%
    left_join(KG_Rubel_Kotteks_Legend, by = c("GRIDCODE"))%>%
    st_transform(crs=st_crs(eu_50raster))%>%
    st_intersection(region_shape)%>%
    group_by(Classification) %>% 
    summarise() #Merge into one multipolygon per Classification

  cm_selection<-climate_matching%>%
    filter(scenario==t)%>%
    left_join(obs_shape[,c("Classification","geometry")], by="Classification")%>%
    st_as_sf()
  
    climate_matching_all<-bind_rows(climate_matching_all, cm_selection)
    
}

climate_matching_all<-climate_matching_all%>%
  st_as_sf()%>%
  mutate(CM_range = cut(perc_climate,
                                   breaks = c(0,10,20,30,40,50,60,70,80,90,100.001),
                                   labels = c(">0-10", ">10-20",">20-30",">30-40",">40-50",">50-60",">60-70",">70-80",">80-90",">90-100"),
                                   right = TRUE))
```


```{r create a vector with long scientific names}
longnames<-c("HS8413","HS1508","HS271","HS6986","HS8116","HS668","HS4242","HS2168","HS164","HS6989","HS3622","HS5333","HS8307","HS2757","HS4583","HS5744","HS5743","HS8309","HS1510","HS5592","HS8035","HS6379", "HS6839","HS974","HS3998","HS6046", "HS3701", "HS4080", "HS8618", "HS4122", "HS7074", "HS806", "HS2503", "HS7164","HS3624", "HS7691", "HS4696", "HS4698", "HS4699","HS5143", "HS6981","HS1428","HS1112","HS6242", "HS6274", "HS8769", "HS4055","HS4056", "HS5247","HS5248","HS6841","HS7339","HS8212","HS2005","HS2782","HS3256", "HS3257","HS3417","HS3624","HS3865","HS3868","HS4576","HS4880","HS4907","HS5605","HS5751","HS7260","HS7326","HS7886","HS8691")

```

# Create maps and export them

```{r create maps}
#Define middle of zoomed in area of graph
mid_x <- 4604652
mid_y <- 6050868

#set progress bar
pb <- progress_bar$new(
 format = "\033[35m Processing [:bar] :current/:total (:percent) in :elapsed \033[0m",
  total = length(unique(maps_data$ID)),
  width = 60,
  clear = FALSE )   


system.time({
  #Export PNGs in parallel execution 
  for(i in unique(maps_data$ID)) {
    
    pb$tick()
    #Store species ID
    species_ID<-i
    
    #Set size of title
    if(species_ID %in% longnames){
      title_size=12
    }else{
      title_size=16
    }
    
    #Get gridcell dataset of this species
    plot_data<-maps_data%>%
      filter(ID==species_ID)
    
    #Get gridcell dataset outside EU of this species
    plot_nonEU_data<-maps_data_outside_EU%>%
      filter(ID==species_ID)
    
    #Get scientific name of the species 
    name<-unique(plot_data$scientificName)
    first_two_words <- sub("^(\\w+\\s+\\w+).*", "\\1", name)  # Extract first two words
    rest_of_name <- sub("^\\w+\\s+\\w+\\s+(.*)", "\\1", name)  # Extract the rest of the name
    
    #Get number of gridcells occupied by the species in the EU and outside EU
    n_gridcells<-unique(plot_data$total_grid_cells)
    n_gridcells_outsideEU<-unique(plot_nonEU_data$total_grid_cells)
    
    #Get thematic group the species belongs to
    thematic_group<-unique(plot_data$Thematic_group)
    
    custom_palette <- c(
      "In EU"="red",
      "Outside EU" =  "#1154f2")
    
    if(thematic_group %in% c("Marine")){
      plot1<-ggplot(plot_data) +
        geom_sf(data = europe, colour = "#636363", fill = "white") + ##575757
        geom_sf(data = EEZ,  colour = "grey80", fill = "#f7fdff")+
        geom_sf(data = region_shape,  colour = "black", fill = "#f0f0f0")+
        geom_tile(aes(x = x, y = y, fill="In EU"), color = "black", width = 50000, height = 50000) +
        geom_tile(data= plot_nonEU_data, aes(x = x, y = y, fill="Outside EU"), color = "black", width = 50000, height = 50000) +
        labs(x = NULL, y = NULL, fill = "Grid Cell") +
        scale_fill_manual(values=custom_palette, 
                          name="Occupied grid cells",
                          breaks = c("In EU", "Outside EU"),
                          drop = FALSE)+
        theme_bw()  +
        annotate("text", x = mid_x-360000, y = mid_y-140000, 
                 label = paste0(n_gridcells," grid cell(s) occupied in EU"), 
                 size = 4, color = "red", fontface = "bold", 
                 hjust = 0.5, vjust = 0)+
        # Second part: Red text
        annotate("text", x = mid_x-360000, y = mid_y -450000, 
                 label =  paste0(n_gridcells_outsideEU," grid cell(s) occupied outside EU"), 
                 size = 4, color = "#1154f2", fontface = "bold", 
                 hjust = 0.5, vjust = 0)+
        coord_sf(xlim = c(1854476, 6605897), 
                 ylim = c(1363659, 5969923))+
        theme(legend.key.size = unit(0.55, "cm"))
      
      #Create an empty plot to fill PDF
      empty_plot <- ggplot() + 
        theme_void() + 
        theme(plot.background = element_blank()) 
      
      #Export only this plot as no climate matching was done for marine species
      plot_final<-plot1 /empty_plot 
      
      # Define the file paths
      plot_png_path <- paste0("./plots/", thematic_group, "/", first_two_words, "_", species_ID, ".png")
      plot_pdf_path <- paste0("./plots/", thematic_group, "/", first_two_words, "_", species_ID, ".pdf")
      
      ggsave(filename = paste0(first_two_words,"_", species_ID, ".png"), plot = plot_final, 
             device = "png", width =8.27 , height = 11.69, path=paste0("./plots/",thematic_group))
      
      # Read the PNG image back in
      img <- image_read(plot_png_path)
      
      # Start a PDF device for output
      pdf(plot_pdf_path, width = 8.27, height = 11.69)
      
      # Create a layout for title and image
      grid.newpage()
      
      # Add title at the top of the PDF
      grid.text(
        label = bquote(italic(.(first_two_words)) ~ .(rest_of_name) ~ "(ID " * .(species_ID) * ")"),
        x = 0.5, y = 0.95, just = "center", gp = gpar(fontsize = title_size, fontface = "bold")
      )
      
      # Add the PNG image below the title
     grid.raster(img, width = unit(0.9, "npc"), height = unit(0.9, "npc"), y = 0.47)
      
      # Close the PDF device
      dev.off()
      
      # Remove the PNG file from the local directory
      file.remove(plot_png_path)
      
  }else{
    
    plot1<-ggplot(plot_data) +
      geom_sf(data = europe, colour = "#636363", fill = "white") + ##575757
      geom_sf(data = EEZ,  colour = "grey80", fill = "#f7fdff")+
      geom_sf(data = region_shape,  colour = "black", fill = "#f0f0f0")+
      geom_tile(aes(x = x, y = y, fill="In EU"), color = "black", width = 50000, height = 50000) +
      geom_tile(data= plot_nonEU_data, aes(x = x, y = y, fill="Outside EU"), color = "black", width = 50000, height = 50000) +
      labs(x = NULL, y = NULL, fill = "Grid Cell") +
      scale_fill_manual(values=custom_palette, 
                        name="Occupied grid cells",
                        breaks = c("In EU", "Outside EU"),
                        drop = FALSE)+
      theme_bw()  +
      annotate("text", x = mid_x-360000, y = mid_y-240000, 
               label = paste0(n_gridcells," grid cell(s) occupied in EU"), 
               size = 4, color = "red", fontface = "bold", 
               hjust = 0.5, vjust = 0)+
      # Second part: Red text
      annotate("text", x = mid_x-360000, y = mid_y -550000, 
               label =  paste0(n_gridcells_outsideEU," grid cell(s) occupied outside EU"), 
               size = 4, color = "#1154f2", fontface = "bold", 
               hjust = 0.5, vjust = 0)+
      coord_sf(xlim = c(1854476, 6605897), #Check that this does not exclude any records: OK
               ylim = c(1363659, 5969923))+
      theme(legend.key.size = unit(0.5, "cm"))
    
    
    #----------------Create plot 2----------------
    
    #Get climate matching data for the selected species 
    cm_data<-climate_matching_all%>%
      filter(ID==species_ID)
    
    #Indicate that all levels should be present for plotting
    all_levels <- c("No match",">0-10", ">10-20", ">20-30", ">30-40", 
                    ">40-50", ">50-60", ">60-70", ">70-80", 
                    ">80-90", ">90-100", "Not calculated")
    
    #Define color palette for the plot
    yl_or_rd_palette <- c(
      "No match"="#f0f0f0",
      ">0-10" =  "#ffffeb", 
      ">10-20" = "#fff7c9",
      ">20-30" = "#ffe894",
      ">30-40" = "#ffd75e",
      ">40-50" = "#FFA500",
      ">50-60" = "#FF6600",
      ">60-70" = "#d93402",
      ">70-80" = "#BD0026", 
      ">80-90" = "#800026", 
      ">90-100"= "#470808",
      "Not calculated" = "white")
    
    
    #Create plot for species that have a match with EU climate
    if(!(all(is.na(cm_data$Classification)))){
      
      #----------------Make plot of first period-------------
      #Store period
      date_range <- str_extract("2001-2025-A1FI", "^\\d{4}-\\d{4}")
      
      #Filter dataset based on species
      cm_current<-cm_data%>%
        filter(scenario=="2001-2025-A1FI")
      
      #Store n totaal
      n_totaal=as.character(unique(cm_current$n_totaal))
      
      stand_occ_pot_current=round(unique(cm_current$ranked_weighted_surface), 2)
      
      #Create plot if climate match data is available for this species under this scenario
      if(!(all(is.na(cm_current$Classification)))){  
        plot2<-ggplot(cm_current) +
          geom_sf(data = st_as_sf(data.frame(CM_range = factor(all_levels, levels = all_levels), geometry = st_sfc(rep(cm_data$geometry[1], length(all_levels))))),
                  aes(fill = CM_range),
                  alpha=NA)+
          geom_sf(data = europe, 
                  aes(fill = "Not calculated"), 
                  colour = "#636363") + ##575757
          geom_sf(data = region_shape, 
                  aes(fill= "No match"), 
                  colour = "black")+
          geom_sf(aes(fill=CM_range))+
          scale_fill_manual(values = yl_or_rd_palette, 
                            name = "Climate match (%)", 
                            breaks = all_levels,
                            drop = FALSE) +
          labs(title = paste0("Climate match for period ", date_range),
               subtitle = "Scenario A1FI (high emissions)",
               x = NULL, 
               y = NULL) +
          annotate("text", 
                   x = mid_x-2860000, #
                   y = mid_y-280000, #
                   label = substitute(italic(n) == value * " (global)", list(value = n_totaal)),   
                   fontface = "bold", 
                   size = 3, 
                   color = "#48494a",
                   hjust = 0,
                   vjust = 0)+
          annotate("text", 
                   x = mid_x-2920000, #
                   y = mid_y+40000, #
                   label = paste("Stand. potential occupancy:",stand_occ_pot_current),   
                   fontface = "bold", 
                   size = 3, 
                   color = "#48494a",
                   hjust = 0,
                   vjust = 0)+
          theme_bw() +
          theme(plot.subtitle = element_text(color = "#636363"),
                legend.key.size = unit(0.55, "cm"))+
          coord_sf(xlim = c(1854476, 6605897), 
                   ylim = c(1363659, 6169923))
      }else{
        
        plot2<-ggplot()+
          geom_sf(data = europe, 
                  colour = "#636363",
                  fill="white") +  ##575757
          geom_sf(data = region_shape, 
                  colour = "black",
                  fill = "#f0f0f0")+
          labs( title = paste0("Climate match for period ", date_range),
                x = NULL,
                y = NULL) +
          theme_bw()  +
          annotate("text",
                   x = mid_x,
                   y = mid_y, 
                   label = "No match with EU climate", 
                   size = 4, color = "red", fontface = "bold", 
                   hjust = 0.5, vjust = 0.75)+
          coord_sf(xlim = c(1854476, 6605897), 
                   ylim = c(1363659, 6169923))
        
        
      }
      
      #----------------Make plot of second period-------------
      #Store period
      date_range <- str_extract("2026-2050-A1FI", "^\\d{4}-\\d{4}")
      
      #Create plot
      cm_future<-cm_data%>%
        filter(scenario=="2026-2050-A1FI")
      
      #Store n totaal
      n_totaal=as.character(unique(cm_future$n_totaal))
      
      #Store stand occ potential
      stand_occ_pot_future=round(unique(cm_future$ranked_weighted_surface), 2)
      
      if(!(all(is.na(cm_future$Classification)))){  
        plot3<-ggplot(cm_future) +
          geom_sf(data = st_as_sf(data.frame(CM_range = factor(all_levels, levels = all_levels), geometry = st_sfc(rep(cm_data$geometry[1], length(all_levels))))),
                  aes(fill = CM_range),
                  alpha=NA)+
          geom_sf(data = europe, 
                  aes(fill = "Not calculated"), 
                  colour = "#636363") + ##575757
          geom_sf(data = region_shape, 
                  aes(fill= "No match"), 
                  colour = "black")+
          geom_sf(aes(fill=CM_range))+
          scale_fill_manual(values = yl_or_rd_palette, 
                            name = "Climate match (%)", 
                            breaks = all_levels,
                            drop = FALSE) +
          labs(title = paste0("Climate match for period ", date_range),
               subtitle = "Scenario A1FI (high emissions)",
               x = NULL, 
               y = NULL) +
          annotate("text", 
                   x = mid_x-2860000, #
                   y = mid_y-280000, #
                   label = substitute(italic(n) == value * " (global)", list(value = n_totaal)),   
                   fontface = "bold", 
                   size = 3, 
                   color = "#48494a",
                   hjust = 0,
                   vjust = 0)+
          annotate("text", 
                   x = mid_x-2920000, #
                   y = mid_y+40000, #
                   label = paste("Stand. potential occupancy:",stand_occ_pot_future),   
                   fontface = "bold", 
                   size = 3, 
                   color = "#48494a",
                   hjust = 0,
                   vjust = 0)+
          theme_bw() +
          theme(plot.subtitle = element_text(color = "#636363"),
                legend.key.size = unit(0.55, "cm"))+
          coord_sf(xlim = c(1854476, 6605897), 
                   ylim = c(1363659, 6169923))
      }else{
        
        plot3<-ggplot()+
          geom_sf(data = europe, 
                  colour = "#636363",
                  fill="white") +  ##575757
          geom_sf(data = region_shape, 
                  colour = "black",
                  fill = "#f0f0f0")+
          labs( title = paste0("Climate match for period ", date_range),
                x = NULL,
                y = NULL) +
          theme_bw()  +
          annotate("text",
                   x = mid_x,
                   y = mid_y, 
                   label = "No match with EU climate", 
                   size = 4, color = "red", fontface = "bold", 
                   hjust = 0.5, vjust = 0.75) +
          coord_sf(xlim = c(1854476, 6605897), 
                   ylim = c(1363659, 6169923))
        
      }        
      
      #Create final plot
      plot_final<-plot1/plot2/plot3 
      
    }else{
      #Create plot 2
      plot2<-ggplot()+
        geom_sf(data = europe, 
                colour = "#636363",
                fill="white") +  ##575757
        geom_sf(data = region_shape, 
                colour = "black",
                fill = "#f0f0f0")+
        labs( x = NULL,
              y = NULL) +
        theme_bw()  +
        annotate("text",
                 x = mid_x,
                 y = mid_y, 
                 label = "No match with EU climate or \nno (reliable) occurrences available to determine match", 
                 size = 4, color = "red", fontface = "bold", 
                 hjust = 0.5, vjust = 0.75) +
        coord_sf(xlim = c(1854476, 6605897), 
                 ylim = c(1363659, 6169923))
      
      #Create final plot
      plot_final<-plot1/plot2 
      
    }
    
    if(thematic_group %in%c("Plants", "Verts", "TER Inverts", "FW Inverts")){
      
      # Define the file paths
      plot_png_path <- paste0("./plots/", thematic_group, "/", first_two_words, "_", species_ID, ".png")
      plot_pdf_path <- paste0("./plots/", thematic_group, "/", first_two_words, "_", species_ID, ".pdf")
      
      # Save each plot as a PDF file
      ggsave(filename = paste0(first_two_words,"_", species_ID, ".png"), plot = plot_final, 
             device = "png", width =8.27 , height = 11.69, path=paste0("./plots/",thematic_group))
      
      # Read the PNG image back in
  img <- image_read(plot_png_path)
  
  # Start a PDF device for output
  pdf(plot_pdf_path, width = 8.27, height = 11.69)
  
  # Create a layout for title and image
  grid.newpage()
  
  # Add title at the top of the PDF
  grid.text(
    label = bquote(italic(.(first_two_words)) ~ .(rest_of_name) ~ "(ID " * .(species_ID) * ")"),
    x = 0.5, y = 0.95, just = "center", gp = gpar(fontsize = title_size, fontface = "bold")
  )
  
  # Add the PNG image below the title
 grid.raster(img, width = unit(0.9, "npc"), height = unit(0.9, "npc"), y = 0.47)
  
  # Close the PDF device
  dev.off()
  
  # Remove the PNG file from the local directory
    file.remove(plot_png_path)
  
    }else{
      # Define the file paths
      plot_png_path <- paste0("./plots/Others/", first_two_words, "_", species_ID, ".png")
      plot_pdf_path <- paste0("./plots/Others/", first_two_words, "_", species_ID, ".pdf")
      
      ggsave(filename = paste0(first_two_words,"_", species_ID, ".png"), plot = plot_final, 
             device = "png", width =8.27 , height = 11.69, path="./plots/Others")
      
      # Read the PNG image back in
  img <- image_read(plot_png_path)
  
  # Start a PDF device for output
  pdf(plot_pdf_path, width = 8.27, height = 11.69)
  
  # Create a layout for title and image
  grid.newpage()
  
  # Add title at the top of the PDF
  grid.text(
    label = bquote(italic(.(first_two_words)) ~ .(rest_of_name) ~ "(ID " * .(species_ID) * ")"),
    x = 0.5, y = 0.95, just = "center", gp = gpar(fontsize = title_size, fontface = "bold")
  )
  
  # Add the PNG image below the title
  grid.raster(img, width = unit(0.9, "npc"), height = unit(0.9, "npc"), y = 0.47)
  
  # Close the PDF device
  dev.off()
  
  # Remove the PNG file from the local directory
    file.remove(plot_png_path)
  
    }
  }
}
  })

```

```{r Combine PDFs into final report}
# Define folders and their output names
folders <- c("./plots/FW Inverts","./plots/Marine","./plots/Plants", "./plots/TER Inverts" ,"./plots/Verts" )
groups <- c( "fw_inverts","marine", "plants","ter_inverts", "verts"  )


#set progress bar
pb <- progress_bar$new(
 format = "\033[35m Processing [:bar] :current/:total (:percent) in :elapsed \033[0m",
  total = length(folders),
  width = 60,
  clear = FALSE                  
)

i<-1

for (folder in folders) {
  #Update progressbar
  pb$tick()
  
  #Get thematic group
  group<-groups[i]
  
  #List all PDF files for that thematic group
  pdf_files <- list.files(folder, pattern = "\\.pdf$", full.names = TRUE)
  
  if (length(pdf_files) == 0) {
    message(paste("No PDF files found in folder:", folder_path))
    return(NULL)
  }

  
   # Define a chunk size, e.g., 100 PDFs per batch
  chunk_size <- 100
  num_chunks <- ceiling(length(pdf_files) / chunk_size)
  
  # Store intermediate batch PDFs
  batch_files <- list()

  # Process PDFs in chunks
  for (j in seq_len(num_chunks)) {
    start_idx <- (j - 1) * chunk_size + 1
    end_idx <- min(j * chunk_size, length(pdf_files))
    batch_pdf_files <- pdf_files[start_idx:end_idx]
    
    # Combine PDFs in the current batch
    batch_output <- paste0(folder, "/", group, "_batch_", j, ".pdf")
    pdf_combine(input = batch_pdf_files, output = batch_output)
    
    # Save the batch file for final combining
    batch_files <- c(batch_files, batch_output)
    
    # Call garbage collector to free memory
    gc()
  }

  # Combine the intermediate batch PDFs into the final combined file
  final_output <- paste0(folder, "/", group, "_combined.pdf")
  pdf_combine(input = batch_files, output = final_output)
  
  # Optionally, remove intermediate batch files after final combination
  file.remove(unlist(batch_files))

  i <- i + 1
}


folder_pdfs <- c("./plots/Report/Report_HS.pdf","./plots/FW Inverts/fw_inverts_combined.pdf","./plots/Marine/marine_combined.pdf","./plots/Plants/plants_combined.pdf", "./plots/TER Inverts/ter_inverts_combined.pdf" ,"./plots/Verts/verts_combined.pdf" )

# Merge all the folder PDFs into the final large PDF
pdf_combine(input = folder_pdfs, 
            output = "./plots/Report/FINAL/HS_Report_final.pdf")

#---------------------Merge the PDF of each thematic group with the report -----------
pdf_combine(input = c("./plots/Report/Report_HS.pdf","./plots/FW Inverts/fw_inverts_combined.pdf"), 
            output = "./plots/Report/FINAL/HS_Report_FW_inverts.pdf")

pdf_combine(input = c("./plots/Report/Report_HS.pdf","./plots/Marine/marine_combined.pdf"), 
            output = "./plots/Report/FINAL/HS_Report_Marine.pdf")

pdf_combine(input = c("./plots/Report/Report_HS.pdf","./plots/Plants/plants_combined.pdf"), 
            output = "./plots/Report/FINAL/HS_Report_Plants.pdf")
 
pdf_combine(input = c("./plots/Report/Report_HS.pdf","./plots/TER Inverts/ter_inverts_combined.pdf"), 
            output = "./plots/Report/FINAL/HS_Report_TER_inverts.pdf")
 
pdf_combine(input = c("./plots/Report/Report_HS.pdf","./plots/Verts/verts_combined.pdf"), 
            output = "./plots/Report/FINAL/HS_Report_Verts.pdf")
```
